server.servlet.context-path=/api
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KC_BASE_URL:'http://keycloak/'}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KC_BASE_URL:'http://keycloak/'}/protocol/openid-connect/certs
app.cors.allowed-origins=http://localhost:3000,https://frontend-mario-rubio-dev.apps.rm1.0a51.p1.openshiftapps.com
# spring-boot-starter-actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
management.endpoint.health.show-details=never
